/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BankApp;

/**
 *
 * @author Admin
 */
public class bank_apply extends javax.swing.JFrame {

    /**
     * Creates new form bank_apply
     */
    public bank_apply() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        jTabbedPane1 = new javax.swing.JTabbedPane();
        ProfileTab = new javax.swing.JPanel();
        FinStat1 = new javax.swing.JLabel();
        Prof1 = new javax.swing.JLabel();
        SuppC1 = new javax.swing.JLabel();
        OtherCC1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_CardType = new javax.swing.JLabel();
        cb_CardType = new javax.swing.JComboBox<>();
        lbl_CardAss = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lbl_Name = new javax.swing.JLabel();
        txt_Name = new javax.swing.JTextField();
        txt_Bdate = new javax.swing.JTextField();
        lbl_Bdate = new javax.swing.JLabel();
        txt_BPlace = new javax.swing.JTextField();
        lbl_BPlace = new javax.swing.JLabel();
        txt_Nat = new javax.swing.JTextField();
        lbl_Nat = new javax.swing.JLabel();
        lbl_Gender = new javax.swing.JLabel();
        txt_Gender = new javax.swing.JTextField();
        txt_CiviStat = new javax.swing.JTextField();
        lbl_CiviStat = new javax.swing.JLabel();
        txt_TinSS = new javax.swing.JTextField();
        lbl_TinSSS = new javax.swing.JLabel();
        LBL_MomMaiden = new javax.swing.JLabel();
        txt_MomMaiden = new javax.swing.JTextField();
        txt_Add = new javax.swing.JTextField();
        lbl_Add = new javax.swing.JLabel();
        lbl_HomeStat = new javax.swing.JLabel();
        txt_HomeStat = new javax.swing.JTextField();
        lbl_HomeZip = new javax.swing.JLabel();
        txt_HomeZip = new javax.swing.JTextField();
        txt_HomeStay = new javax.swing.JTextField();
        lbl_HomeStay = new javax.swing.JLabel();
        Bt_Cancel1 = new javax.swing.JButton();
        bt_Next1 = new javax.swing.JButton();
        txt_Emale = new javax.swing.JTextField();
        lbl_Email = new javax.swing.JLabel();
        lbl_mobile = new javax.swing.JLabel();
        txt_mobile = new javax.swing.JTextField();
        lbl_HomeTele = new javax.swing.JLabel();
        txt_HomeTele = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField2 = new javax.swing.JTextField();
        lbl_CardAss1 = new javax.swing.JLabel();
        txt_Add1 = new javax.swing.JTextField();
        lbl_Add1 = new javax.swing.JLabel();
        lbl_CardAss2 = new javax.swing.JLabel();
        lbl_CardAss3 = new javax.swing.JLabel();
        lbl_CardAss4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        lbl_CardAss5 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        lbl_CardAss6 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        lbl_CardAss7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txt_Add2 = new javax.swing.JTextField();
        lbl_Add2 = new javax.swing.JLabel();
        txt_Add3 = new javax.swing.JTextField();
        lbl_Add3 = new javax.swing.JLabel();
        Bt_Cancel2 = new javax.swing.JButton();
        bt_Next2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Credit Card Application");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 102, 102));
        setPreferredSize(new java.awt.Dimension(1123, 950));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        ProfileTab.setBackground(new java.awt.Color(255, 255, 255));
        ProfileTab.setPreferredSize(new java.awt.Dimension(1121, 800));

        FinStat1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        FinStat1.setForeground(new java.awt.Color(153, 153, 153));
        FinStat1.setText("Financial Status");

        Prof1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        Prof1.setForeground(new java.awt.Color(237, 199, 3));
        Prof1.setText("Profile");

        SuppC1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        SuppC1.setForeground(new java.awt.Color(153, 153, 153));
        SuppC1.setText("Supplementary Card");

        OtherCC1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        OtherCC1.setForeground(new java.awt.Color(153, 153, 153));
        OtherCC1.setText("Other Credit Card");

        jSeparator1.setBackground(new java.awt.Color(237, 199, 3));
        jSeparator1.setForeground(new java.awt.Color(237, 199, 3));

        lbl_CardType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_CardType.setForeground(new java.awt.Color(153, 153, 153));
        lbl_CardType.setText("Card Type");

        cb_CardType.setForeground(new java.awt.Color(153, 153, 153));
        cb_CardType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_CardType.setBorder(null);
        cb_CardType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_CardTypeActionPerformed(evt);
            }
        });

        lbl_CardAss.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_CardAss.setForeground(new java.awt.Color(153, 153, 153));
        lbl_CardAss.setText("Card Assigned Name");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("jTextField1");
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        lbl_Name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Name.setForeground(new java.awt.Color(153, 153, 153));
        lbl_Name.setText("Name");

        txt_Name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Name.setForeground(new java.awt.Color(153, 153, 153));
        txt_Name.setText("jTextField1");
        txt_Name.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        txt_Bdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Bdate.setForeground(new java.awt.Color(153, 153, 153));
        txt_Bdate.setText("jTextField1");
        txt_Bdate.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        lbl_Bdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Bdate.setForeground(new java.awt.Color(153, 153, 153));
        lbl_Bdate.setText("Birthdate");

        txt_BPlace.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_BPlace.setForeground(new java.awt.Color(153, 153, 153));
        txt_BPlace.setText("jTextField1");
        txt_BPlace.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        lbl_BPlace.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_BPlace.setForeground(new java.awt.Color(153, 153, 153));
        lbl_BPlace.setText("Birthplace");

        txt_Nat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Nat.setForeground(new java.awt.Color(153, 153, 153));
        txt_Nat.setText("jTextField1");
        txt_Nat.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        lbl_Nat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Nat.setForeground(new java.awt.Color(153, 153, 153));
        lbl_Nat.setText("Nationality");

        lbl_Gender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Gender.setForeground(new java.awt.Color(153, 153, 153));
        lbl_Gender.setText("Gender");

        txt_Gender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Gender.setForeground(new java.awt.Color(153, 153, 153));
        txt_Gender.setText("jTextField1");
        txt_Gender.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        txt_CiviStat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_CiviStat.setForeground(new java.awt.Color(153, 153, 153));
        txt_CiviStat.setText("jTextField1");
        txt_CiviStat.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        lbl_CiviStat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_CiviStat.setForeground(new java.awt.Color(153, 153, 153));
        lbl_CiviStat.setText("Civil Status");

        txt_TinSS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_TinSS.setForeground(new java.awt.Color(153, 153, 153));
        txt_TinSS.setText("jTextField1");
        txt_TinSS.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        lbl_TinSSS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_TinSSS.setForeground(new java.awt.Color(153, 153, 153));
        lbl_TinSSS.setText("TIN-SSS No.");

        LBL_MomMaiden.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LBL_MomMaiden.setForeground(new java.awt.Color(153, 153, 153));
        LBL_MomMaiden.setText("Mother's Maiden Name");

        txt_MomMaiden.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_MomMaiden.setForeground(new java.awt.Color(153, 153, 153));
        txt_MomMaiden.setText("jTextField1");
        txt_MomMaiden.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        txt_Add.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Add.setForeground(new java.awt.Color(153, 153, 153));
        txt_Add.setText("jTextField1");
        txt_Add.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        lbl_Add.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Add.setForeground(new java.awt.Color(153, 153, 153));
        lbl_Add.setText("Address");

        lbl_HomeStat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_HomeStat.setForeground(new java.awt.Color(153, 153, 153));
        lbl_HomeStat.setText("Homeownership Status");

        txt_HomeStat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_HomeStat.setForeground(new java.awt.Color(153, 153, 153));
        txt_HomeStat.setText("jTextField1");
        txt_HomeStat.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        lbl_HomeZip.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_HomeZip.setForeground(new java.awt.Color(153, 153, 153));
        lbl_HomeZip.setText("Home Zip");

        txt_HomeZip.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_HomeZip.setForeground(new java.awt.Color(153, 153, 153));
        txt_HomeZip.setText("jTextField1");
        txt_HomeZip.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        txt_HomeZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_HomeZipActionPerformed(evt);
            }
        });

        txt_HomeStay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_HomeStay.setForeground(new java.awt.Color(153, 153, 153));
        txt_HomeStay.setText("jTextField1");
        txt_HomeStay.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        txt_HomeStay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_HomeStayActionPerformed(evt);
            }
        });

        lbl_HomeStay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_HomeStay.setForeground(new java.awt.Color(153, 153, 153));
        lbl_HomeStay.setText("Home Length Stay");

        Bt_Cancel1.setBackground(new java.awt.Color(204, 204, 204));
        Bt_Cancel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        Bt_Cancel1.setForeground(new java.awt.Color(51, 51, 51));
        Bt_Cancel1.setText("Cancel");
        Bt_Cancel1.setBorder(null);
        Bt_Cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Cancel1ActionPerformed(evt);
            }
        });

        bt_Next1.setBackground(new java.awt.Color(237, 199, 3));
        bt_Next1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        bt_Next1.setForeground(new java.awt.Color(51, 51, 51));
        bt_Next1.setText("Next");
        bt_Next1.setBorder(null);
        bt_Next1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Next1ActionPerformed(evt);
            }
        });

        txt_Emale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Emale.setForeground(new java.awt.Color(153, 153, 153));
        txt_Emale.setText("jTextField1");
        txt_Emale.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        lbl_Email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Email.setForeground(new java.awt.Color(153, 153, 153));
        lbl_Email.setText("Email");

        lbl_mobile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_mobile.setForeground(new java.awt.Color(153, 153, 153));
        lbl_mobile.setText("Mobile Phone");

        txt_mobile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_mobile.setForeground(new java.awt.Color(153, 153, 153));
        txt_mobile.setText("jTextField1");
        txt_mobile.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        txt_mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mobileActionPerformed(evt);
            }
        });

        lbl_HomeTele.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_HomeTele.setForeground(new java.awt.Color(153, 153, 153));
        lbl_HomeTele.setText("Home Telephone");

        txt_HomeTele.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_HomeTele.setForeground(new java.awt.Color(153, 153, 153));
        txt_HomeTele.setText("jTextField1");
        txt_HomeTele.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        txt_HomeTele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_HomeTeleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProfileTabLayout = new javax.swing.GroupLayout(ProfileTab);
        ProfileTab.setLayout(ProfileTabLayout);
        ProfileTabLayout.setHorizontalGroup(
            ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileTabLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileTabLayout.createSequentialGroup()
                        .addComponent(Prof1)
                        .addGap(221, 221, 221)
                        .addComponent(FinStat1)
                        .addGap(212, 212, 212)
                        .addComponent(OtherCC1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                        .addComponent(SuppC1))
                    .addGroup(ProfileTabLayout.createSequentialGroup()
                        .addGroup(ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_CardType, 0, 415, Short.MAX_VALUE)
                            .addComponent(lbl_CardType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addGroup(ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addComponent(lbl_CardAss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(ProfileTabLayout.createSequentialGroup()
                        .addComponent(txt_Name)
                        .addGap(60, 60, 60)
                        .addGroup(ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Bdate, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Bdate, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_BPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_BPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfileTabLayout.createSequentialGroup()
                        .addGroup(ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Nat, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Nat, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_CiviStat, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(lbl_CiviStat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_TinSSS, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(txt_TinSS)))
                    .addGroup(ProfileTabLayout.createSequentialGroup()
                        .addGroup(ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LBL_MomMaiden, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_MomMaiden)
                            .addComponent(txt_HomeStat, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addComponent(lbl_HomeStat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addGroup(ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Add)
                            .addComponent(lbl_Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(ProfileTabLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_mobile)
                                        .addComponent(lbl_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_HomeZip, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                        .addComponent(lbl_HomeZip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_HomeStay)
                                    .addComponent(lbl_HomeStay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_HomeTele)
                                    .addComponent(lbl_HomeTele, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(ProfileTabLayout.createSequentialGroup()
                        .addGroup(ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Emale)
                            .addComponent(lbl_Email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(60, 60, 60))
            .addGroup(ProfileTabLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(Bt_Cancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_Next1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        ProfileTabLayout.setVerticalGroup(
            ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileTabLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Prof1)
                    .addComponent(SuppC1)
                    .addComponent(OtherCC1)
                    .addComponent(FinStat1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_CardType)
                    .addComponent(lbl_CardAss))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_CardType, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ProfileTabLayout.createSequentialGroup()
                        .addComponent(lbl_Name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfileTabLayout.createSequentialGroup()
                        .addGroup(ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_BPlace)
                            .addComponent(lbl_Bdate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_BPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Bdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfileTabLayout.createSequentialGroup()
                        .addComponent(lbl_CiviStat)
                        .addGap(12, 12, 12)
                        .addComponent(txt_CiviStat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ProfileTabLayout.createSequentialGroup()
                                .addComponent(lbl_Nat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_Nat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ProfileTabLayout.createSequentialGroup()
                                .addComponent(lbl_Gender)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(ProfileTabLayout.createSequentialGroup()
                            .addComponent(lbl_TinSSS)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_TinSS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ProfileTabLayout.createSequentialGroup()
                        .addComponent(LBL_MomMaiden)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_MomMaiden, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfileTabLayout.createSequentialGroup()
                        .addComponent(lbl_Add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ProfileTabLayout.createSequentialGroup()
                        .addComponent(lbl_HomeStat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_HomeStat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfileTabLayout.createSequentialGroup()
                        .addComponent(lbl_HomeZip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_HomeZip, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfileTabLayout.createSequentialGroup()
                        .addComponent(lbl_HomeStay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_HomeStay, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ProfileTabLayout.createSequentialGroup()
                        .addComponent(lbl_Email)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Emale, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfileTabLayout.createSequentialGroup()
                        .addComponent(lbl_mobile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfileTabLayout.createSequentialGroup()
                        .addComponent(lbl_HomeTele)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_HomeTele, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(ProfileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bt_Cancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Next1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        jTabbedPane1.addTab("tab1", ProfileTab);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Profile");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(237, 199, 3));
        jLabel6.setText("Financial Status");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Other Credit Card");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Supplementary Card");

        jSeparator2.setBackground(new java.awt.Color(237, 199, 3));
        jSeparator2.setForeground(new java.awt.Color(237, 199, 3));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2.setText("jTextField1");
        jTextField2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        lbl_CardAss1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_CardAss1.setForeground(new java.awt.Color(153, 153, 153));
        lbl_CardAss1.setText("Company Name");

        txt_Add1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Add1.setForeground(new java.awt.Color(153, 153, 153));
        txt_Add1.setText("jTextField1");
        txt_Add1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        lbl_Add1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Add1.setForeground(new java.awt.Color(153, 153, 153));
        lbl_Add1.setText("Company Address");

        lbl_CardAss2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_CardAss2.setForeground(new java.awt.Color(153, 153, 153));
        lbl_CardAss2.setText("Company Zip");

        lbl_CardAss3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_CardAss3.setForeground(new java.awt.Color(153, 153, 153));
        lbl_CardAss3.setText("Company Stay");

        lbl_CardAss4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_CardAss4.setForeground(new java.awt.Color(153, 153, 153));
        lbl_CardAss4.setText("Work Nature");

        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        jTextField5.setText("jTextField1");
        jTextField5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        lbl_CardAss5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_CardAss5.setForeground(new java.awt.Color(153, 153, 153));
        lbl_CardAss5.setText("Position");

        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(153, 153, 153));
        jTextField6.setText("jTextField1");
        jTextField6.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        jTextField7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(153, 153, 153));
        jTextField7.setText("jTextField1");
        jTextField7.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        lbl_CardAss6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_CardAss6.setForeground(new java.awt.Color(153, 153, 153));
        lbl_CardAss6.setText("Employment Status");

        jTextField8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(153, 153, 153));
        jTextField8.setText("jTextField1");
        jTextField8.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        jTextField9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(153, 153, 153));
        jTextField9.setText("jTextField1");
        jTextField9.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        jTextField10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(153, 153, 153));
        jTextField10.setText("jTextField1");
        jTextField10.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        lbl_CardAss7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_CardAss7.setForeground(new java.awt.Color(153, 153, 153));
        lbl_CardAss7.setText("Email");

        jSeparator5.setBackground(new java.awt.Color(237, 199, 3));
        jSeparator5.setForeground(new java.awt.Color(237, 199, 3));

        txt_Add2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Add2.setForeground(new java.awt.Color(153, 153, 153));
        txt_Add2.setText("jTextField1");
        txt_Add2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        lbl_Add2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Add2.setForeground(new java.awt.Color(153, 153, 153));
        lbl_Add2.setText("Source of Funds");

        txt_Add3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Add3.setForeground(new java.awt.Color(153, 153, 153));
        txt_Add3.setText("jTextField1");
        txt_Add3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        lbl_Add3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Add3.setForeground(new java.awt.Color(153, 153, 153));
        lbl_Add3.setText("Gross Annual Salarary");

        Bt_Cancel2.setBackground(new java.awt.Color(204, 204, 204));
        Bt_Cancel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        Bt_Cancel2.setForeground(new java.awt.Color(51, 51, 51));
        Bt_Cancel2.setText("Cancel");
        Bt_Cancel2.setBorder(null);
        Bt_Cancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_Cancel2ActionPerformed(evt);
            }
        });

        bt_Next2.setBackground(new java.awt.Color(237, 199, 3));
        bt_Next2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        bt_Next2.setForeground(new java.awt.Color(51, 51, 51));
        bt_Next2.setText("Next");
        bt_Next2.setBorder(null);
        bt_Next2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Next2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_CardAss5, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(60, 60, 60)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField7)
                                            .addComponent(lbl_CardAss6, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                                            .addComponent(lbl_CardAss7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_CardAss2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(60, 60, 60)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_CardAss3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(51, 51, 51)
                                        .addComponent(jTextField9))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(221, 221, 221)
                                        .addComponent(jLabel6)
                                        .addGap(212, 212, 212)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                                        .addComponent(jLabel8))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_CardAss1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_Add1)
                                            .addComponent(lbl_Add1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(211, 211, 211)
                                                .addComponent(lbl_CardAss4, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addComponent(jSeparator5))
                                .addGap(10, 10, 10)))
                        .addGap(50, 50, 50))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Add2)
                            .addComponent(lbl_Add2, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Add3, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Add3, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(Bt_Cancel2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_Next2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_CardAss1)
                            .addComponent(lbl_Add1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(txt_Add1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_CardAss2)
                    .addComponent(lbl_CardAss3)
                    .addComponent(lbl_CardAss4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_CardAss6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_CardAss5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_CardAss7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Add2)
                    .addComponent(lbl_Add3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Add2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Add3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bt_Cancel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Next2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Profile");

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Financial Status");

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Other Credit Card");

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Supplementary Card");

        jSeparator3.setBackground(new java.awt.Color(237, 199, 3));
        jSeparator3.setForeground(new java.awt.Color(237, 199, 3));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(221, 221, 221)
                        .addComponent(jLabel10)
                        .addGap(212, 212, 212)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                        .addComponent(jLabel12)))
                .addGap(60, 60, 60))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab3", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel13.setText("Profile");

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel14.setText("Financial Status");

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel15.setText("Other Credit Card");

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel16.setText("Supplementary Card");

        jSeparator4.setBackground(new java.awt.Color(237, 199, 3));
        jSeparator4.setForeground(new java.awt.Color(237, 199, 3));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator4)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(221, 221, 221)
                        .addComponent(jLabel14)
                        .addGap(212, 212, 212)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                        .addComponent(jLabel16)))
                .addGap(60, 60, 60))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab4", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1111, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_CardTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_CardTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_CardTypeActionPerformed

    private void txt_HomeZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_HomeZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_HomeZipActionPerformed

    private void txt_HomeStayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_HomeStayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_HomeStayActionPerformed

    private void bt_Next1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Next1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_Next1ActionPerformed

    private void Bt_Cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Cancel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bt_Cancel1ActionPerformed

    private void txt_mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mobileActionPerformed

    private void txt_HomeTeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_HomeTeleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_HomeTeleActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void Bt_Cancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_Cancel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bt_Cancel2ActionPerformed

    private void bt_Next2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Next2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_Next2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bank_apply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bank_apply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bank_apply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bank_apply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bank_apply().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Cancel1;
    private javax.swing.JButton Bt_Cancel2;
    private javax.swing.JLabel FinStat1;
    private javax.swing.JLabel LBL_MomMaiden;
    private javax.swing.JLabel OtherCC1;
    private javax.swing.JLabel Prof1;
    private javax.swing.JPanel ProfileTab;
    private javax.swing.JLabel SuppC1;
    private javax.swing.JButton bt_Next1;
    private javax.swing.JButton bt_Next2;
    private javax.swing.JComboBox<String> cb_CardType;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lbl_Add;
    private javax.swing.JLabel lbl_Add1;
    private javax.swing.JLabel lbl_Add2;
    private javax.swing.JLabel lbl_Add3;
    private javax.swing.JLabel lbl_BPlace;
    private javax.swing.JLabel lbl_Bdate;
    private javax.swing.JLabel lbl_CardAss;
    private javax.swing.JLabel lbl_CardAss1;
    private javax.swing.JLabel lbl_CardAss2;
    private javax.swing.JLabel lbl_CardAss3;
    private javax.swing.JLabel lbl_CardAss4;
    private javax.swing.JLabel lbl_CardAss5;
    private javax.swing.JLabel lbl_CardAss6;
    private javax.swing.JLabel lbl_CardAss7;
    private javax.swing.JLabel lbl_CardType;
    private javax.swing.JLabel lbl_CiviStat;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_Gender;
    private javax.swing.JLabel lbl_HomeStat;
    private javax.swing.JLabel lbl_HomeStay;
    private javax.swing.JLabel lbl_HomeTele;
    private javax.swing.JLabel lbl_HomeZip;
    private javax.swing.JLabel lbl_Name;
    private javax.swing.JLabel lbl_Nat;
    private javax.swing.JLabel lbl_TinSSS;
    private javax.swing.JLabel lbl_mobile;
    private javax.swing.JTextField txt_Add;
    private javax.swing.JTextField txt_Add1;
    private javax.swing.JTextField txt_Add2;
    private javax.swing.JTextField txt_Add3;
    private javax.swing.JTextField txt_BPlace;
    private javax.swing.JTextField txt_Bdate;
    private javax.swing.JTextField txt_CiviStat;
    private javax.swing.JTextField txt_Emale;
    private javax.swing.JTextField txt_Gender;
    private javax.swing.JTextField txt_HomeStat;
    private javax.swing.JTextField txt_HomeStay;
    private javax.swing.JTextField txt_HomeTele;
    private javax.swing.JTextField txt_HomeZip;
    private javax.swing.JTextField txt_MomMaiden;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JTextField txt_Nat;
    private javax.swing.JTextField txt_TinSS;
    private javax.swing.JTextField txt_mobile;
    // End of variables declaration//GEN-END:variables
}
